/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kurtspace.chat.message;

import com.google.inject.Guice;
import com.kurtspace.chat.message.guice.MessageModule;

import org.gwizard.rest.RestModule;
import org.gwizard.services.Run;

public class App {

    public static void main(String[] args) {
        Guice.createInjector(new MessageModule(), new RestModule()).getInstance(Run.class).start();
    }
}
